### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Rasmuss1en** [mrsmook/music-discord-heroku-bot#3]
when i try to run the bot, nothing happends and when i click open app this is what comes up.

https://gyazo.com/c15406553668a765f190ccaecc5e23f6

**Comment by Rasmuss1en** [comment]
https://gyazo.com/752811d21682999ff97aab5511c5ab61?token=a2a94334529b181f99e9c544d6af4ef5

**Comment by milaputeri** [comment]
i have same problem

**Comment by Rasmuss1en** [comment]
can you fix it?=

**Comment by mrsmook** [comment]
issue corrected you can test it again or drop old bot and build new one.
